# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CESNET.
#
# Invenio OpenID Connect is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

env:
  matrix:
    - REQUIREMENTS=release EXTRAS=tests

python:
  - "3.8"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder pip-tools"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.in"
  - "pip-compile -U --verbose -o .travis-release-requirements.txt .travis-release-requirements.in"
  - cat .travis-release-requirements.txt

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "cat .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[$EXTRAS]"
  - "travis_retry pip install -e tests"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "Gfmy58tJVjbbsNoRjmjHaluaDNjHHhJgajBmpnyNUx0jlNqmT4lL3X5eKaT3KD1pUQ5X0KUMH5Fosz1yhwdqyHBksQW4ciqbjcaBJMTNFpJkm0jPosc1Fbjm3NSM7HvzJyDaWGBqmFDJtFwdzZ5mPvpV+9z8eP0DJuqRZEtAeJ2lK7pTgQqsLCfSAIbKXC69PSIiRj6VEiju9eace5P2YvGHRy7SDhXnxV4q3/p/AfY1RykJn/oOhbz28LOH2Arhf1FMKaLcrSS6oyH0DZZKP1GGROx3dHlvyzLl0hyEDTgKX+rZJDrCFCI2R6L+qFArXV+cFSv0QtUng4mONc2eIoxRNYm3M35EwPNMRRlvNkCeD1KJepLrhmRah2cd2ysFaV27VR+2K/rewRTuvF6rODkMpC+AKNz38efKlLLZ4+th4bspklkycVZcWwoz3DU5nGu9HyDTs7zAsone67mA1UmH3+KTqWE0z3gWnJRobl0+SlzxV65tyIaLPRO8/xwh0IN3cGaU0NL3O4CY+DT6SI2agFnQQM8w2Gr5BI50LuD/fdZVwHDugK0/rf2moAEGD5U5kJLYsiuNwDETQzEP0MLU/nF2a1rEMpDxsS4Ui5kBfXE9WMf8G7tye0XYyOdvMXfW9KUKjA0fxNwyAHxtfqFd35PxBuhgDf6lFs+gITk="
  on:
    tags: true
    branch: master
  distributions: "sdist bdist_wheel"
  skip_existing: true
